### ISSUE TITLE
Run results in a bunch of warnings

### ISSUE THREAD

**Issue by mike-solomon** [openrewrite/rewrite-recipe-markdown-generator#58]
When I check out this project and run the `run` command, I get a bunch of warnings.

Example warning: 

```
[main] WARN org.openrewrite.config.ClasspathScanningLoader - Unable to configure org.openrewrite.java.security.ZipSlip
java.lang.NoClassDefFoundError: Could not initialize class org.openrewrite.java.security.ZipSlip
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.openrewrite.internal.RecipeIntrospectionUtils.construct(RecipeIntrospectionUtils.java:133)
	at org.openrewrite.internal.RecipeIntrospectionUtils.constructRecipe(RecipeIntrospectionUtils.java:102)
	at org.openrewrite.config.ClasspathScanningLoader.scanClasses(ClasspathScanningLoader.java:142)
	at org.openrewrite.config.ClasspathScanningLoader.<init>(ClasspathScanningLoader.java:86)
	at org.openrewrite.config.Environment$Builder.scanJar(Environment.java:237)
	at org.openrewrite.RecipeMarkdownGenerator.run(RecipeMarkdownGenerator.kt:117)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at org.openrewrite.RecipeMarkdownGenerator$Companion.main(RecipeMarkdownGenerator.kt:1416)
	at org.openrewrite.RecipeMarkdownGenerator.main(RecipeMarkdownGenerator.kt)
```

It looks like something weird is going on with the `ZipSlip` recipe.

**Comment by knutwannheden** [comment]
Possibly a dependency on rewrite-analysis is missing somewhere.

**Comment by mike-solomon** [comment]
@knutwannheden I tried adding `rewrite-analysis` to the `build.gradle` file and I got this error: 
![image](https://github.com/openrewrite/rewrite-recipe-markdown-generator/assets/1187834/8255812a-a25d-4c33-a4c2-fdce88de259f)

**Comment by mike-solomon** [comment]
Looking like `rewrite-analysis` has a group of `meta` instead of `recipe`. Adding `"recipe"("org.openrewrite.meta:rewrite-analysis:$rewriteVersion")` brought in the `rewrite-analysis` - but did not fix the warnings around `ZipSlip`.

**Comment by knutwannheden** [comment]
I think if you were to set `rewriteVersion` to `latest.integration` it might work.

**Comment by mike-solomon** [comment]
👍 -- setting it to `latest.integration` did appear to eliminate the error (in addition to adding analysis). Theoretically that means that one we do a release somewhere this problem should resolve itself.

**Comment by mike-solomon** [comment]
Confirming that the latest releases have fixed this. I no longer get warnings running the generator. Thanks @knutwannheden - closing.
